### ISSUE TITLE
As a player, I want to see the guesses of all players, the correct solution, the painting as well as the current leader board and who will paint next  after every round.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-client#72]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-server#93
- [x] sopra-fs23-group-25/Pictionary-client#45
- [x] sopra-fs23-group-25/Pictionary-server#95
- [x] sopra-fs23-group-25/Pictionary-client#46
- [x] sopra-fs23-group-25/Pictionary-client#47
- [x] sopra-fs23-group-25/Pictionary-client#82

### acceptance criteria

- [x] The player scores are updated correctly. The new scores and corresponding usernames 
are shown on screen.
- [x] The answers of the players and points distributed between them are displayed, as well 
as the painters final image.
- [x] The username of the painter in the upcoming round is shown to all players.
